site_name: DOE Reports Extractor (DOE Extractor)
theme:
    name: readthedocs
nav:
   - Home: 'index.md'
   - Installation: 'installation.md'
   - Usage: 'usage.md'
   - Contributing: 'contributing.md'
   - Authors: 'authors.md'
   - History: 'history.md'
